name: goreleaser-linux

on:
  push:
    tags: #vX.X.Xというタグのときにリリースする
      - "v[0-9]+.[0-9]+.[0-9]+-linux"
jobs:
  goreleaser-linux:
    # choosing-github-hosted-runners - Workflow syntax for GitHub Actions - GitHub Docs
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-18.04
    permissions:
      contents: write # これがないとリリースを作成できない
    steps:
      -
        name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Put goreleaser.yml
        run: cp goreleaser-linux.yml .goreleaser.yml
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          # environment-variables - GitHub Actions - GoReleaser https://goreleaser.com/ci/actions/#environment-variables
          # i-3 - GitHub Actionsの使い方 | 純規の暇人趣味ブログ https://jyn.jp/github-actions-usage/#i-3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
